name: Deploy a preview of the docs

# Default to bash
defaults:
    run:
        shell: bash

on:
    pull_request:
        types: [opened, synchronize]
        branches:
            - main
            - dev

jobs:
    deploy_preview:
        name: Deploy Preview
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - uses: Genez-io/genezio-github-action@main
              with:
                  token: ${{ secrets.GENEZIO_TOKEN }}
            - name: Build Docs
              run: npx docusaurus build --out-dir public
            - name: Compute stage
              run: echo "STAGE=$(echo -n ${GITHUB_REF##*/} | shasum | head -c 8)" >> $GITHUB_ENV
            - name: Deploy
              run: genezio deploy --frontend --stage $STAGE
            - uses: actions/github-script@v7
              with:
                  script: |
                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: `👋 Your preview is ready! ${process.env["STAGE"]}`
                      })
