# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  notify_cicd_repo:
    runs-on: ubuntu-latest
    steps:
    - name: Notify CI/CD Repository & Open PR
      env:
        GH_TOKEN: ${{ secrets.NOTIFY_CICD_PAT }}
      run: |
        #!/bin/bash
        gh workflow run release -R Genez-io/deployapps-landing-page
